[
    [
        "mainmenu",
        "plugin.video.elementum/movies/trakt/trending",
        "widget",
        "plugin"
    ],
    [
        "mainmenu",
        "plugin.video.elementum/movies/trakt/trending",
        "widgetPath",
        "plugin://plugin.video.elementum/movies/trakt/trending"
    ],
    [
        "mainmenu",
        "plugin.video.elementum/movies/trakt/trending",
        "icon",
        "special://skin/extras/icons/film.png"
    ],
    [
        "mainmenu",
        "mubicinema",
        "widget",
        "plugin"
    ],
    [
        "mainmenu",
        "mubicinema",
        "widgetPath",
        "plugin://plugin.video.turecomendador/?action=mubi"
    ],
    [
        "mainmenu",
        "mubicinema",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "mainmenu",
        "seguimientomovies-trakt",
        "widget",
        "plugin"
    ],
    [
        "mainmenu",
        "seguimientomovies-trakt",
        "widgetPath",
        "plugin://plugin.video.turecomendador/?action=watchlist_movies"
    ],
    [
        "mainmenu",
        "seguimientomovies-trakt",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "mainmenu",
        "tvshows",
        "widget",
        "plugin"
    ],
    [
        "mainmenu",
        "tvshows",
        "widgetPath",
        "plugin://plugin.video.turecomendador/?action=shows"
    ],
    [
        "mainmenu",
        "tvshows",
        "icon",
        "special://skin/extras/icons/tv.png"
    ],
    [
        "mainmenu",
        "0",
        "icon",
        "special://skin/extras/icons/addons.png"
    ],
    [
        "mainmenu",
        "settings",
        "icon",
        "special://skin/extras/icons/settings.png"
    ],
    [
        "mainmenu",
        "33060",
        "icon",
        "special://skin/extras/icons/power.png"
    ]
]